name: Build Dream APK

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Java
      uses: actions/setup-java@v4
      with:
        java-version: '8'
        distribution: 'temurin'
        
    - name: Install Android SDK
      run: |
        yes | sdkmanager "platforms;android-34" "build-tools;34.0.0"
        
    - name: Build APK
      run: |
        cd app
        ../gradlew assembleDebug --no-daemon --stacktrace
        
    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: MyDream-App
        path: app/build/outputs/apk/debug/app-debug.apk
