name: Build Dream APK

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout dreams
      uses: actions/checkout@v4
      
    - name: Setup Java for dreams
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        
    - name: Install Gradle
      run: |
        wget -q https://services.gradle.org/distributions/gradle-8.4-bin.zip
        unzip -q gradle-8.4-bin.zip
        echo "GRADLE_HOME=$PWD/gradle-8.4" >> $GITHUB_ENV
        echo "$PWD/gradle-8.4/bin" >> $GITHUB_PATH
        
    - name: Build Dream APK
      run: |
        cd app
        gradle assembleDebug --stacktrace --no-daemon
        
    - name: Upload Dream APK
      if: success()
      uses: actions/upload-artifact@v4
      with:
        name: MyDream-App
        path: app/build/outputs/apk/debug/app-debug.apk
        retention-days: 1
