name: Build Dream APK

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Java
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        
    - name: Setup Android SDK
      uses: android-actions/setup-android@v3
      
    - name: Debug project structure
      run: |
        echo "=== هيكل المشروع ==="
        find app -type f -name "*.kt" -o -name "*.java" -o -name "*.gradle" -o -name "*.xml"
        echo "=== محتوى build.gradle ==="
        cat app/build.gradle
        
    - name: Build APK with full logs
      run: |
        cd app
        gradle clean assembleDebug --no-daemon --stacktrace --info
        
    - name: Upload APK
      if: success()
      uses: actions/upload-artifact@v4
      with:
        name: MyDream-App
        path: app/build/outputs/apk/debug/app-debug.apk
